import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { createServer as createNetServer } from 'node:net';
import ExcelJS from 'exceljs';
import { createApp } from '../server/app.js';
import { createStorage } from '../server/storage.js';
import { rowsFromPaste, rowsFromXlsx } from '../server/roster.js';

test('pegar tablas y leer XLSX conserva solo Usuario, Apellido y Nombre',async()=>{
  const pasted=rowsFromPaste('| Apellido | Nombre |\n| --- | --- |\n| Soto Luna | Ana María |\n| | |\n| Pérez Prado | Berta Elena |');
  assert.equal(pasted.length,2);assert.equal(pasted[0].lastName,'Soto Luna');
  assert.deepEqual(Object.keys(pasted[0]),['institutionalUser','lastName','firstName','sourceRow']);
  const csv=rowsFromPaste('Usuario,Apellido,Nombre\ninst-1,"Ruiz, Aranda",Clara');
  assert.equal(csv[0].lastName,'Ruiz, Aranda');
  const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Sheet1');
  sheet.addRow(['Aula: 3520043 - Sistemas I']);sheet.addRow(['Reporte de ejemplo']);sheet.addRow([]);
  sheet.addRow(['Usuario','Apellido','Nombre','Calificación','Retroalimentación']);
  sheet.addRow(['Usuario','Apellido','Nombre','Calificación','Retroalimentación']);
  sheet.addRow(['inst-42','Soto Luna','Ana María',98,'Información privada que no debe importarse']);
  sheet.addRow(['inst-43','Pérez Prado','Berta Elena',77,'Tampoco se importa']);
  const rows=await rowsFromXlsx(Buffer.from(await workbook.xlsx.writeBuffer()));
  assert.equal(rows.length,2);assert.equal(rows[0].institutionalUser,'inst-42');
  assert.equal(rows[1].firstName,'Berta Elena');
  assert.ok(!JSON.stringify(rows).includes('Calificación'));assert.ok(!JSON.stringify(rows).includes('Información privada'));
});

test('sesión docente, materias, reimportación y cupos se cumplen en servidor',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'aula-admin-test-'));
  const path=join(directory,'data.sqlite'),storage=createStorage(path);
  const adminPassword=randomBytes(24).toString('hex');
  const free=createNetServer();await new Promise(resolve=>free.listen(0,'127.0.0.1',resolve));const port=free.address().port;free.close();
  const origin=`http://127.0.0.1:${port}`;
  const server=createApp({storage,adminUsername:'docente',adminPassword,publicOrigin:origin});
  await new Promise(resolve=>server.listen(port,'127.0.0.1',resolve));
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));storage.close();rmSync(directory,{recursive:true,force:true});});
  let cookie='',csrf='';
  async function request(route,{method='GET',body,authorized=false,withCsrf=true,originHeader=true}={}){
    const headers={};if(body!==undefined)headers['Content-Type']='application/json';
    if(originHeader&&method!=='GET')headers.Origin=origin;
    if(authorized)headers.Cookie=cookie;
    if(authorized&&withCsrf)headers['X-CSRF-Token']=csrf;
    const response=await fetch(origin+route,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});
    const text=await response.text();let data;try{data=JSON.parse(text);}catch{data=text;}
    return {response,data};
  }
  assert.equal((await request('/api/admin/courses')).response.status,401);
  assert.equal((await request('/api/admin/login',{method:'POST',body:{username:'docente',password:'incorrecta'}})).response.status,401);
  assert.equal((await request('/api/admin/login',{method:'POST',body:{username:'docente',password:adminPassword},originHeader:false})).response.status,403);
  const login=await request('/api/admin/login',{method:'POST',body:{username:'docente',password:adminPassword}});
  assert.equal(login.response.status,200);csrf=login.data.csrf;cookie=login.response.headers.get('set-cookie').split(';')[0];
  assert.match(login.response.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  assert.equal((await request('/api/admin/courses',{method:'POST',body:{name:'Sistemas I'},authorized:true,withCsrf:false})).response.status,403);
  const made=await request('/api/admin/courses',{method:'POST',body:{name:'Sistemas I · Registros'},authorized:true});
  assert.equal(made.response.status,201);const course=made.data.course,code=course.code;
  assert.match(code,/^MAT-[A-Z2-9]{5}-[A-Z2-9]{5}-[A-Z2-9]{5}$/);
  assert.ok(!JSON.stringify((await request('/api/admin/courses',{authorized:true})).data).includes(code));
  assert.equal((await request('/api/student/course',{method:'POST',body:{code}})).data.course.name,'Sistemas I · Registros');
  for(let n=0;n<10;n++)assert.equal((await request('/api/student/course',{method:'POST',body:{code}})).response.status,200);
  assert.equal((await request('/api/student/course',{method:'POST',body:{code:'OTRO-CODIGO'}})).response.status,404);
  const topic=await request(`/api/admin/courses/${course.id}/topics`,{method:'POST',body:{name:'Redes',instructions:'Trabajo colaborativo',capacity:1},authorized:true});
  assert.equal(topic.response.status,201);const topicId=topic.data.topic.id;
  const roster='Usuario\tApellido\tNombre\tNota\ninst-1\tSoto Luna\tAna María\t98\ninst-2\tPérez Prado\tBerta Elena\t77';
  const preview=await request(`/api/admin/courses/${course.id}/roster/preview`,{method:'POST',body:{text:roster},authorized:true});
  assert.deepEqual(preview.data.rows.map(row=>row.status),['new','new']);
  assert.equal((await request(`/api/admin/courses/${course.id}/roster/import`,{method:'POST',body:{text:roster},authorized:true})).response.status,400);
  const imported=await request(`/api/admin/courses/${course.id}/roster/import`,{method:'POST',body:{text:roster,confirmed:true},authorized:true});
  assert.equal(imported.data.result.added,2);
  const list=await request(`/api/admin/courses/${course.id}`,{authorized:true});
  assert.equal(list.data.students.length,2);
  assert.ok(list.data.students.every(student=>!('grade' in student)&&!('note' in student)));
  const first=list.data.students.find(s=>s.institutionalUser==='inst-1'),second=list.data.students.find(s=>s.institutionalUser==='inst-2');
  const assignment=await request(`/api/admin/courses/${course.id}/students/${first.id}`,{method:'PATCH',body:{firstName:'Ana',lastName:first.lastName,topicId},authorized:true});
  assert.equal(assignment.response.status,200);
  const full=await request(`/api/admin/courses/${course.id}/students/${second.id}`,{method:'PATCH',body:{firstName:second.firstName,lastName:second.lastName,topicId},authorized:true});
  assert.equal(full.response.status,400);assert.match(full.data.error,/cupo/);
  assert.equal((await request(`/api/admin/courses/${course.id}/topics/${topicId}`,{method:'PATCH',body:{name:'Redes',instructions:'',capacity:0},authorized:true})).response.status,400);
  const repeat=await request(`/api/admin/courses/${course.id}/roster/import`,{method:'POST',body:{text:roster,confirmed:true},authorized:true});
  assert.equal(repeat.data.result.added,0);assert.equal(repeat.data.result.skipped,2);
  const preserved=(await request(`/api/admin/courses/${course.id}`,{authorized:true})).data.students.find(s=>s.id===first.id);
  assert.equal(preserved.firstName,'Ana');assert.equal(preserved.topicId,topicId);
  const other=(await request('/api/admin/courses',{method:'POST',body:{name:'Sistemas II'},authorized:true})).data.course;
  assert.equal((await request(`/api/admin/courses/${other.id}/students/${first.id}`,{method:'PATCH',body:{firstName:'Ana',lastName:'Soto',topicId:null},authorized:true})).response.status,404);
  assert.equal((await request(`/api/admin/courses/${other.id}/students`,{method:'POST',body:{firstName:'Otra',lastName:'Persona',institutionalUser:'',allowDuplicate:false},authorized:true})).response.status,201);
  assert.equal((await request(`/api/admin/courses/${course.id}/students/${first.id}`,{method:'PATCH',body:{firstName:'Ana',lastName:'Soto',topicId:'a'.repeat(32)},authorized:true})).response.status,400);
  const exportResult=await request(`/api/admin/courses/${course.id}/export`,{authorized:true});
  assert.equal(exportResult.response.status,200);assert.match(exportResult.data,/Soto Luna/);
  const rotated=await request(`/api/admin/courses/${course.id}/rotate`,{method:'POST',body:{},authorized:true});
  assert.notEqual(rotated.data.code,code);assert.equal((await request('/api/student/course',{method:'POST',body:{code}})).response.status,404);
  assert.equal((await request('/api/admin/logout',{method:'POST',authorized:true})).response.status,200);
  assert.equal((await request('/api/admin/me',{authorized:true})).response.status,401);
  const reopened=createStorage(path);t.after(()=>reopened.close());
  assert.equal(reopened.getStudents(course.id).length,2);assert.equal(reopened.getTopics(course.id)[0].members,1);
});
